[package]
name = "passless-rs"
description = "FIDO2 security token emulator"
categories = ["command-line-utilities"]
keywords = ["passkeys", "fido2", "auth", "password-manager", "pass"]
authors.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true

[[bin]]
name = "passless"
path = "src/main.rs"

[dependencies]
passless-core.workspace = true
soft-fido2.workspace = true
soft-fido2-transport.workspace = true
log.workspace = true
env_logger.workspace = true
sha2.workspace = true
serde_cbor.workspace = true
serde.workspace = true
prs-lib.workspace = true
serde_json.workspace = true
libc.workspace = true
nix.workspace = true
notify-rust.workspace = true
tss-esapi.workspace = true
aes-gcm.workspace = true
rand.workspace = true
hex.workspace = true
ctrlc.workspace = true
clap.workspace = true

[dev-dependencies]
base64 = "0.22"
ciborium = "0.2"
tempfile = "3.14"

[build-dependencies]
passless-core.workspace = true
clap.workspace = true
clap_complete.workspace = true
